### ISSUE TITLE
Villagers only get jobs from birch fletching tables

### ISSUE THREAD

**Issue by santastolle** [pnk2u/More-Fletching-Tables#7] opened 2024-09-06 00:56 UTC
v1.6.0
MC v1.21

Villagers only get jobs from birch fletching tables.

**Comment by pnk2u** [comment] 2024-09-06 11:16
Thanks for reporting this, unfortunately I cannot reproduce it on my side, what other mods did you have installed when this happened?

**Comment by santastolle** [comment] 2024-09-06 16:02
Thanks for the quick response! The culprit was Visual Workbench. For some reason it recognizes the fletching tables as crafting tables. The birch fletching table works fine.

**Comment by pnk2u** [comment] 2024-09-06 18:45
Ah, I see, thanks for finding that out for me, much appreciated, it should then be fixed in version 1.6.1.

**Comment by santastolle** [comment] 2024-09-07 00:12
You are an absolute legend. Cheers!

**Closed as completed** 2024-09-07 01:12 UTC
